onEvent('recipes', event => {
    //Machine recipe : 
    event.recipes.custommachinery.custom_machine("robosstweaks:creative_fabricator", 200)
    .requireEnergyPerTick(1000)
    .requireItem(Item.of("robosstweaks:robotboss_ingot"), "input1")
    .requireItem(Item.of("robosstweaks:kikongin_ingot"), "input3")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input2")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input4")
    .requireItem(Item.of("ae2:item_storage_cell_256k"), "input5")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input6")
    .requireItem(Item.of("robosstweaks:laimx_ingot", "input7"))
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input8")
    .requireItem(Item.of("robosstweaks:blakdestroyer_ingot", "input9"))
    .produceItem(Item.of("ae2:creative_item_cell"), "output1")
    .requireStructure([["a a","   ","a a"],[" a ","aba"," m "]],{"a":"robosstweaks:creative_catalyst","b":"avaritia:infinity_block"})

    event.recipes.custommachinery.custom_machine("robosstweaks:creative_fabricator", 200)
    .requireEnergyPerTick(1000)
    .requireItem(Item.of("robosstweaks:robotboss_ingot"), "input1")
    .requireItem(Item.of("robosstweaks:kikongin_ingot"), "input3")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input2")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input4")
    .requireItem(Item.of("ae2:fluid_storage_cell_256k"), "input5")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input6")
    .requireItem(Item.of("robosstweaks:laimx_ingot", "input7"))
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input8")
    .requireItem(Item.of("robosstweaks:blakdestroyer_ingot", "input9"))
    .produceItem(Item.of("ae2:creative_fluid_cell"), "output1")
    .requireStructure([["a a","   ","a a"],[" a ","aba"," m "]],{"a":"robosstweaks:creative_catalyst","b":"avaritia:infinity_block"})

    event.recipes.custommachinery.custom_machine("robosstweaks:creative_fabricator", 200)
    .requireEnergyPerTick(1000)
    .requireItem(Item.of("robosstweaks:robotboss_ingot"), "input1")
    .requireItem(Item.of("robosstweaks:kikongin_ingot"), "input3")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input2")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input4")
    .requireItem(Item.of("appbot:mana_storage_cell_256k"), "input5")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input6")
    .requireItem(Item.of("robosstweaks:laimx_ingot", "input7"))
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input8")
    .requireItem(Item.of("robosstweaks:blakdestroyer_ingot", "input9"))
    .produceItem(Item.of("appbot:creative_mana_cell"), "output1")
    .requireStructure([["a a","   ","a a"],[" a ","aba"," m "]],{"a":"robosstweaks:creative_catalyst","b":"avaritia:infinity_block"})

    event.recipes.custommachinery.custom_machine("robosstweaks:creative_fabricator", 200)
    .requireEnergyPerTick(1000)
    .requireItem(Item.of("robosstweaks:robotboss_ingot"), "input1")
    .requireItem(Item.of("robosstweaks:kikongin_ingot"), "input3")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input2")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input4")
    .requireItem(Item.of("appmek:chemical_storage_cell_256k"), "input5")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input6")
    .requireItem(Item.of("robosstweaks:laimx_ingot", "input7"))
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input8")
    .requireItem(Item.of("robosstweaks:blakdestroyer_ingot", "input9"))
    .produceItem(Item.of("appmek:creative_chemical_cell"), "output1")
    .requireStructure([["a a","   ","a a"],[" a ","aba"," m "]],{"a":"robosstweaks:creative_catalyst","b":"avaritia:infinity_block"})

  event.recipes.custommachinery.custom_machine("robosstweaks:creative_fabricator", 200)
    .requireEnergyPerTick(1000)
    .requireItem(Item.of("robosstweaks:robotboss_ingot"), "input1")
    .requireItem(Item.of("robosstweaks:kikongin_ingot"), "input3")
    .requireItem(Item.of("avaritia:infinity_ingot"), "input2")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input4")
    .requireItem(Item.of("draconicevolution:draconium_chest"), "input5")
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input6")
    .requireItem(Item.of("robosstweaks:laimx_ingot", "input7"))
    .requireItem(Item.of("avaritia:infinity_catalyst"), "input8")
    .requireItem(Item.of("robosstweaks:blakdestroyer_ingot", "input9"))
    .produceItem(Item.of("create:creative_crate"), "output1")
    .requireStructure([["a a","   ","a a"],[" a ","aba"," m "]],{"a":"robosstweaks:creative_catalyst","b":"avaritia:infinity_block"})

  })