onEvent('jei.hide.items', event => {
    event.hide([
                //other
                'avaritia:quartz_singularity', 
                'avaritia:redstone_singularity', 
                'avaritia:lapis_singularity', 
                'avaritia:gold_singularity', 
                'avaritia:iron_singularity', 
                'avaritia:emerald_singularity', 
                'avaritia:extreme_crafting_table', 
                'avaritia:silver_singularity', 
                'avaritia:compressed_crafting_table', 
                Item.of('ae2:facade', '{item:"twilightforest:uncrafting_table"}'), 
                'cyclic:uncrafter', 
                'twilightforest:uncrafting_table', 
                'avaritia:amethyst_singularity', 
                'avaritia:netherite_singularity', 
                'avaritia:iridium_singularity', 
                'avaritia:platinum_singularity', 
                'avaritia:fluxed_singularity', 
                'avaritia:compressor', 
                'avaritia:diamond_singularity', 
                'avaritia:copper_singularity', 
                'avaritia:tin_singularity', 
                'avaritia:lead_singularity', 
                'avaritia:nickel_singularity', 
                'avaritia:double_compressed_crafting_table',
                //lead
                'immersiveengineering:deepslate_ore_lead', 
                'immersiveengineering:raw_block_lead', 
                'immersiveengineering:raw_lead', 
                'immersiveengineering:storage_lead', 
                'immersiveengineering:ingot_lead', 
                'immersiveengineering:dust_lead', 
                'immersiveengineering:plate_lead', 
                'immersiveengineering:nugget_lead', 
                'immersiveengineering:slab_storage_lead', 
                'create:crushed_lead_ore', 
                'mekanism:nugget_lead', 
                'mekanism:dust_lead', 
                'mekanism:ingot_lead', 
                'mekanism:block_lead', 
                'mekanism:raw_lead', 
                'mekanism:block_raw_lead', 
                'mekanism:deepslate_lead_ore', 
                'mekanism:lead_ore', 
                'immersiveengineering:ore_lead',
                Item.of('ae2:facade', '{item:"mekanism:block_lead"}'),
                Item.of('ae2:facade', '{item:"mekanism:block_raw_lead"}'),
                Item.of('ae2:facade', '{item:"mekanism:lead_ore"}'),
                Item.of('ae2:facade', '{item:"immersiveengineering:ore_lead"}'),
                Item.of('ae2:facade', '{item:"immersiveengineering:raw_block_lead"}'),
                Item.of('ae2:facade', '{item:"immersiveengineering:storage_lead"}'),
                Item.of('ae2:facade', '{item:"mekanism:deepslate_lead_ore"}'),
                //copper
                Item.of('iceandfire:copper_hoe'), 
                Item.of('iceandfire:copper_shovel'), 
                Item.of('iceandfire:copper_axe'), 
                Item.of('iceandfire:copper_pickaxe'), 
                Item.of('iceandfire:copper_sword'), 
                'iceandfire:copper_nugget', 
                'iceandfire:copper_ore', 
                'iceandfire:copper_block', 
                'iceandfire:copper_ingot', 
                'create:crushed_copper_ore', 
                'create:copper_sheet', 
                'immersiveengineering:plate_copper', 
                'immersiveengineering:wire_copper', 
                'immersiveengineering:dust_copper', 
                'mekanism:dust_copper', 
                'create:copper_nugget', 
                'tconstruct:copper_nugget', 
                'immersiveengineering:nugget_copper', 
                'cyclic:copper_nugget',
                //bronze
                'mekanism:dust_bronze', 
                'mekanism:ingot_bronze', 
                'mekanism:nugget_bronze', 
                'mekanism:block_bronze',
                //osmium
                'create:crushed_raw_osmium',
                'mekanism:dust_quartz', 
                'mekanism:block_tin', 
                'mekanism:ingot_tin', 
                'mekanism:deepslate_tin_ore', 
                'mekanism:tin_ore', 
                'create:crushed_raw_aluminum', 
                'mekanism:dust_netherite', 
                'cyclic:netherite_nugget', 
                'tconstruct:netherite_nugget', 
                'create:crushed_raw_tin', 
                'mekanism:nugget_tin', 
                'mekanism:raw_tin', 
                'mekanism:dust_tin', 
                'mekanism:block_raw_tin',
                'mekanism:dust_emerald', 
                'mekanism:dust_diamond', 
                'createaddition:diamond_grit', 
                'industrialforegoing:diamond_gear',
                //amethyst
                'iceandfire:amythest_ore',
                'iceandfire:amythest_block',
                'iceandfire:amythest_gem',
                Item.of('ae2:facade', '{item:"iceandfire:amythest_block"}'),
                Item.of('ae2:facade', '{item:"iceandfire:amythest_ore"}'),
                'immersiveengineering:deepslate_ore_silver', 
                'immersiveengineering:ore_silver', 
                'iceandfire:silver_ore', 
                'iceandfire:silver_block', 
                Item.of('ae2:facade', '{item:"mekanism:block_bronze"}'), 
                'immersiveengineering:nugget_silver', 
                'immersiveengineering:raw_block_silver', 
                'immersiveengineering:storage_silver', 
                'immersiveengineering:slab_storage_silver', 
                'immersiveengineering:dust_silver', 
                'immersiveengineering:plate_silver', 
                'immersiveengineering:raw_silver', 
                'immersiveengineering:ingot_silver', 
                Item.of('ae2:facade', '{item:"immersiveengineering:sheetmetal_silver"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:ore_silver"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:deepslate_ore_silver"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:raw_block_silver"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:storage_silver"}'), 
                Item.of('ae2:facade', '{item:"iceandfire:silver_ore"}'),
                'create:crushed_raw_silver',
                Item.of('ae2:facade', '{item:"iceandfire:silver_block"}'),
                Item.of('ae2:facade', '{item:"immersiveengineering:ore_uranium"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:deepslate_ore_uranium"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:raw_block_uranium"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:storage_uranium"}'), 
                'create:crushed_raw_uranium', 
                'immersiveengineering:ore_uranium', 
                'immersiveengineering:deepslate_ore_uranium', 
                'immersiveengineering:raw_block_uranium', 
                'immersiveengineering:storage_uranium', 
                'immersiveengineering:slab_storage_uranium', 
                'immersiveengineering:ingot_uranium', 
                'immersiveengineering:nugget_uranium', 
                'immersiveengineering:raw_uranium', 
                'immersiveengineering:dust_uranium'
            ])
  })