onEvent('rei.hide.items', event => {
    event.hide([
                //other
                'avaritia:quartz_singularity', 
                'avaritia:redstone_singularity', 
                'avaritia:lapis_singularity', 
                'avaritia:gold_singularity', 
                'avaritia:iron_singularity', 
                'avaritia:emerald_singularity', 
                'avaritia:extreme_crafting_table', 
                'avaritia:silver_singularity', 
                'avaritia:compressed_crafting_table', 
                Item.of('ae2:facade', '{item:"twilightforest:uncrafting_table"}'), 
                'cyclic:uncrafter', 
                'twilightforest:uncrafting_table', 
                'avaritia:amethyst_singularity', 
                'avaritia:netherite_singularity', 
                'avaritia:iridium_singularity', 
                'avaritia:platinum_singularity', 
                'avaritia:fluxed_singularity', 
                'avaritia:compressor', 
                'avaritia:diamond_singularity', 
                'avaritia:copper_singularity', 
                'avaritia:tin_singularity', 
                'avaritia:lead_singularity', 
                'avaritia:nickel_singularity', 
                'avaritia:double_compressed_crafting_table',
                //lead
                'immersiveengineering:deepslate_ore_lead', 
                'immersiveengineering:raw_block_lead', 
                'immersiveengineering:raw_lead', 
                'immersiveengineering:storage_lead', 
                'immersiveengineering:ingot_lead', 
                'immersiveengineering:dust_lead', 
                'immersiveengineering:plate_lead', 
                'immersiveengineering:nugget_lead', 
                'immersiveengineering:slab_storage_lead', 
                'create:crushed_lead_ore', 
                'mekanism:nugget_lead', 
                'mekanism:dust_lead', 
                'mekanism:ingot_lead', 
                'mekanism:block_lead', 
                'mekanism:raw_lead', 
                'mekanism:block_raw_lead', 
                'mekanism:deepslate_lead_ore', 
                'mekanism:lead_ore', 
                'immersiveengineering:ore_lead',
                Item.of('ae2:facade', '{item:"mekanism:block_lead"}'),
                Item.of('ae2:facade', '{item:"mekanism:block_raw_lead"}'),
                Item.of('ae2:facade', '{item:"mekanism:lead_ore"}'),
                Item.of('ae2:facade', '{item:"immersiveengineering:ore_lead"}'),
                Item.of('ae2:facade', '{item:"immersiveengineering:raw_block_lead"}'),
                Item.of('ae2:facade', '{item:"immersiveengineering:storage_lead"}'),
                Item.of('ae2:facade', '{item:"mekanism:deepslate_lead_ore"}'),
                //copper
                Item.of('iceandfire:copper_hoe'), 
                Item.of('iceandfire:copper_shovel'), 
                Item.of('iceandfire:copper_axe'), 
                Item.of('iceandfire:copper_pickaxe'), 
                Item.of('iceandfire:copper_sword'), 
                'iceandfire:copper_nugget', 
                'iceandfire:copper_ore', 
                'iceandfire:copper_block', 
                'iceandfire:copper_ingot', 
                'create:crushed_copper_ore', 
                'create:copper_sheet', 
                'immersiveengineering:plate_copper', 
                'immersiveengineering:wire_copper', 
                'immersiveengineering:dust_copper', 
                'mekanism:dust_copper', 
                'create:copper_nugget', 
                'tconstruct:copper_nugget', 
                'immersiveengineering:nugget_copper', 
                'cyclic:copper_nugget',
                //bronze
                'mekanism:dust_bronze', 
                'mekanism:ingot_bronze', 
                'mekanism:nugget_bronze', 
                'mekanism:block_bronze',
                //osmium
                'create:crushed_raw_osmium',
                'mekanism:dust_quartz', 
                'mekanism:block_tin', 
                'mekanism:ingot_tin', 
                'mekanism:deepslate_tin_ore', 
                'mekanism:tin_ore', 
                'create:crushed_raw_aluminum', 
                'mekanism:dust_netherite', 
                'cyclic:netherite_nugget', 
                'tconstruct:netherite_nugget', 
                'create:crushed_raw_tin', 
                'mekanism:nugget_tin', 
                'mekanism:raw_tin', 
                'mekanism:dust_tin', 
                'mekanism:block_raw_tin',
                'mekanism:dust_emerald', 
                'mekanism:dust_diamond', 
                'createaddition:diamond_grit', 
                'industrialforegoing:diamond_gear',
                //amethyst
                'iceandfire:amythest_ore',
                'iceandfire:amythest_block',
                'iceandfire:amythest_gem',
                Item.of('ae2:facade', '{item:"iceandfire:amythest_block"}'),
                Item.of('ae2:facade', '{item:"iceandfire:amythest_ore"}'),
                'immersiveengineering:deepslate_ore_silver', 
                'immersiveengineering:ore_silver', 
                'iceandfire:silver_ore', 
                'iceandfire:silver_block', 
                Item.of('ae2:facade', '{item:"mekanism:block_bronze"}'), 
                'immersiveengineering:nugget_silver', 
                'immersiveengineering:raw_block_silver', 
                'immersiveengineering:storage_silver', 
                'immersiveengineering:slab_storage_silver', 
                'immersiveengineering:dust_silver', 
                'immersiveengineering:plate_silver', 
                'immersiveengineering:raw_silver', 
                'immersiveengineering:ingot_silver', 
                Item.of('ae2:facade', '{item:"immersiveengineering:sheetmetal_silver"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:ore_silver"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:deepslate_ore_silver"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:raw_block_silver"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:storage_silver"}'), 
                Item.of('ae2:facade', '{item:"iceandfire:silver_ore"}'),
                'create:crushed_raw_silver',
                Item.of('ae2:facade', '{item:"iceandfire:silver_block"}'),
                Item.of('ae2:facade', '{item:"immersiveengineering:ore_uranium"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:deepslate_ore_uranium"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:raw_block_uranium"}'), 
                Item.of('ae2:facade', '{item:"immersiveengineering:storage_uranium"}'), 
                'create:crushed_raw_uranium', 
                'immersiveengineering:ore_uranium', 
                'immersiveengineering:deepslate_ore_uranium', 
                'immersiveengineering:raw_block_uranium', 
                'immersiveengineering:storage_uranium', 
                'immersiveengineering:slab_storage_uranium', 
                'immersiveengineering:ingot_uranium', 
                'immersiveengineering:nugget_uranium', 
                'immersiveengineering:raw_uranium', 
                'immersiveengineering:dust_uranium',
                'createappliedkinetics:energy_provider',
                'iceandfire:silver_nugget',
                'iceandfire:silver_ingot',
                Item.of('ae2:facade', '{item:"immersiveengineering:deepslate_ore_lead"}'),
                Item.of('ae2:facade', '{item:"iceandfire:copper_ore"}'),
                Item.of('ae2:facade', '{item:"iceandfire:copper_block"}'),
                'immersiveengineering:stick_iron',
                Item.of('ae2:facade', '{item:"mekanism:block_raw_tin"}'),
                Item.of('ae2:facade', '{item:"mekanism:block_tin"}'),
                'mekanism:sawdust',
                'immersiveengineering:dust_wood',
                'mekanism:dust_lapis_lazuli',
                'thermal:ender_pearl_dust', 
                'thermal:rose_gold_plate', 
                'immersiveengineering:plate_gold', 
                'immersiveengineering:plate_iron', 
                'immersiveengineering:plate_steel', 
                'immersiveengineering:plate_electrum', 
                'immersiveengineering:plate_constantan', 
                'immersiveengineering:plate_nickel', 
                'immersiveengineering:dust_sulfur', 
                'mekanism:dust_sulfur', 
                'beyond_earth:iron_stick', 
                'immersiveengineering:storage_constantan', 
                'immersiveengineering:slab_storage_constantan', 
                'immersiveengineering:dust_constantan', 
                'immersiveengineering:nugget_constantan', 
                'immersiveengineering:ingot_constantan', 
                'immersiveengineering:ore_nickel', 
                'immersiveengineering:deepslate_ore_nickel', 
                'immersiveengineering:raw_block_nickel', 
                'immersiveengineering:storage_nickel', 
                'immersiveengineering:slab_storage_nickel', 
                'immersiveengineering:ingot_nickel', 
                'immersiveengineering:nugget_nickel', 
                'immersiveengineering:raw_nickel', 
                'immersiveengineering:dust_nickel', 
                'immersiveengineering:slab_storage_electrum', 
                'immersiveengineering:storage_electrum', 
                'createaddition:electrum_spool', 
                'immersiveengineering:wire_electrum', 
                'immersiveengineering:ingot_electrum', 
                'immersiveengineering:nugget_electrum', 
                'immersiveengineering:dust_electrum', 
                'createaddition:electrum_sheet', 
                'createaddition:electrum_nugget', 
                'createaddition:electrum_ingot',
                'create:golden_sheet', 
                'create:crushed_raw_gold', 
                'immersiveengineering:dust_gold', 
                'create:crushed_raw_iron', 
                'industrialforegoing:iron_gear', 
                'immersiveengineering:dust_iron', 
                'mekanism:dust_iron', 
                'create:iron_sheet', 
                'beyond_earth:iron_plate', 
                'immersiveengineering:armor_steel_legs', 
                'immersiveengineering:armor_steel_chest',
                'immersiveengineering:armor_steel_head', 
                'thermal:steel_block', 
                'beyond_earth:steel_nugget', 
                'beyond_earth:steel_ingot', 
                'beyond_earth:steel_block', 
                'mekanism:block_steel', 
                'immersiveengineering:armor_steel_feet', 
                'immersiveengineering:sword_steel', 
                'immersiveengineering:hoe_steel', 
                'immersiveengineering:axe_steel', 
                'immersiveengineering:shovel_steel',
                'immersiveengineering:pickaxe_steel',
                 'mekanism:nugget_steel', 
                 'mekanism:dust_steel', 
                 'mekanism:ingot_steel', 
                 'immersiveengineering:dust_steel', 
                 'immersiveengineering:nugget_steel', 
                 'immersiveengineering:ingot_steel', 
                 'industrialforegoing:gold_gear', 
                 'mekanism:dust_gold',
                 Item.of('extendedcrafting:singularity', '{Id:"extendedcrafting:platinum"}'),
                 Item.of('ae2:facade', '{item:"immersiveengineering:storage_electrum"}'), 
                 Item.of('ae2:facade', '{item:"immersiveengineering:storage_constantan"}'), 
                 Item.of('ae2:facade', '{item:"immersiveengineering:storage_nickel"}'), 
                 Item.of('ae2:facade', '{item:"mekanism:block_steel"}'), 
                 Item.of('ae2:facade', '{item:"thermal:steel_block"}'), 
                 Item.of('ae2:facade', '{item:"beyond_earth:steel_block"}'),
                 'zerocore:debugtool',
                 'create:crushed_raw_copper',
                 'thermal:rose_gold_block', 
                 'thermal:rose_gold_ingot', 
                 'thermal:rose_gold_nugget', 
                 'thermal:rose_gold_dust', 
                 'thermal:rose_gold_gear', 
                 'thermal:rose_gold_coin',
                 Item.of('ae2:facade', '{item:"thermal:rose_gold_block"}'),
                 'appmek:creative_chemical_cell',
                 'ae2:creative_fluid_cell',
                 'appbot:creative_mana_cell',
                 'doggytalents:creative_radar', 
                 'create:handheld_worldshaper', 
                 'rftoolspower:dimensionalcell_creative', 
                 Item.of('tconstruct:creative_slot', '{slot:"upgrades"}'), 
                 'botania:corporea_spark_creative', 
                 'botania:lens_storm', 
                 'botania:infrangible_platform', 
                 'ae2:creative_energy_cell', 
                 'integrateddynamics:energy_battery_creative', 
                 'create:creative_fluid_tank', 
                 'immersiveengineering:capacitor_creative', 
                 'rftoolsutility:creative_screen', 
                 'mekanism:creative_bin', 
                 'simplyjetpacks:jetpack_creative_armored', 
                 'simplyjetpacks:jetpack_creative', 
                 'doggytalents:creative_collar', 
                 'twilightforest:glass_sword', 
                 'cyclic:battery_infinite', 'createaddition:creative_energy', 
                 Item.of('tconstruct:creative_slot', '{slot:"souls"}'), 
                 Item.of('tconstruct:creative_slot', '{slot:"abilities"}'), 
                 Item.of('tconstruct:creative_slot', '{slot:"defense"}'),
                 'thermal:machine_catalyst_creative_augment',
                 'thermal:machine_efficiency_creative_augment',
                 'thermal:fluid_tank_creative_augment',
                 'thermal:rf_coil_creative_augment',
                 'buildinggadgets:construction_paste_container_creative',
                 'iceandfire:creative_dragon_meal',
                 'powah:energy_cell_creative',
                 'bigreactors:reinforced_turbinecreativesteamgenerator',
                 'bigreactors:basic_turbinecreativesteamgenerator',
                 'bigreactors:reinforced_reactorcreativewatergenerator',
                 'industrialforegoing:transporter'
            ])
  })