onEvent('recipes', e => {

const orecraft=[
    {
        out:"thermal:silver_ore",
        in:"thermal:raw_silver"
    },{
        out:"bigreactors:yellorite_ore",
        in:"bigreactors:yellorium_ingot"
    },{
        out:"immersiveengineering:ore_aluminum",
        in:"immersiveengineering:raw_aluminum"
    },{
        out:"draconicevolution:overworld_draconium_ore",
        in:"draconicevolution:draconium_dust"
    },{
        out:"thermal:niter_ore",
        in:"thermal:niter"
    },{
        out:"powah:uraninite_ore",
        in:"powah:uraninite"
    },{
        out:"rftoolsbase:dimensionalshard_overworld",
        in:"rftoolsbase:dimensionalshard"
    },{
        out:"thermal:sulfur_ore",
        in:"thermal:sulfur"
    },{
        out:"ae2:quartz_ore",
        in:"ae2:certus_quartz_crystal"
    },{
        out:"create:zinc_ore",
        in:"create:raw_zinc"
    },{
        out:"thermal:nickel_ore",
        in:"thermal:raw_nickel"
    },{
        out:"thermal:cinnabar_ore",
        in:"thermal:cinnabar"
    },{
        out:"thermal:apatite_ore",
        in:"thermal:apatite"
    }
]
orecraft.forEach((ore)=>{
    e.custom({
        "type":"mekanism:combining",
        "mainInput":{
            "amount":8,
            "ingredient":{
                "item":ore.in
            }
        },
        "extraInput":{
            "ingredient":{
                "tag":"forge:cobblestone/normal"
            }
        },
        "output":{
                "item":ore.out
            }
        })
    })


    const deeporecraft=[
        {
            out:"thermal:deepslate_silver_ore",
            in:"thermal:raw_silver"
        },{
            out:"immersiveengineering:deepslate_ore_aluminum",
            in:"immersiveengineering:raw_aluminum"
        },{
            out:"draconicevolution:deepslate_draconium_ore",
            in:"draconicevolution:draconium_dust"
        },{
            out:"thermal:deepslate_niter_ore",
            in:"thermal:niter"
        },{
            out:"powah:deepslate_uraninite_ore",
            in:"powah:uraninite"
        },{
            out:"thermal:deepslate_sulfur_ore",
            in:"thermal:sulfur"
        },{
            out:"ae2:deepslate_quartz_ore",
            in:"ae2:certus_quartz_crystal"
        },{
            out:"create:deepslate_zinc_ore",
            in:"create:raw_zinc"
        },{
            out:"thermal:deepslate_nickel_ore",
            in:"thermal:raw_nickel"
        },{
            out:"thermal:deepslate_cinnabar_ore",
            in:"thermal:cinnabar"
        },{
            out:"thermal:deepslate_apatite_ore",
            in:"thermal:apatite"
        }
    ]
    deeporecraft.forEach((ore)=>{
        e.custom({
            "type":"mekanism:combining",
            "mainInput":{
                "amount":8,
                "ingredient":{
                    "item":ore.in
                }
            },
            "extraInput":{
                "ingredient":{
                    "tag":"forge:cobblestone/deepslate"
                }
            },
            "output":{
                    "item":ore.out
                }
            })
        })

        const netherorecraft=[
            {
                out:"tconstruct:cobalt_ore",
                in:"tconstruct:raw_cobalt"
            },{
                out:"rftoolsbase:dimensionalshard_nether",
                in:"rftoolsbase:dimensionalshard"
            },{
                out:"draconicevolution:nether_draconium_ore",
                in:"draconicevolution:draconium_dust"
            }
        ]
        netherorecraft.forEach((ore)=>{
            e.custom({
                "type":"mekanism:combining",
                "mainInput":{
                    "amount":8,
                    "ingredient":{
                        "item":ore.in
                    }
                },
                "extraInput":{
                    "ingredient":{
                        "tag":"forge:netherrack"
                    }
                },
                "output":{
                        "item":ore.out
                    }
                })
            })


            const endorecraft=[
                {
                    out:"rftoolsbase:dimensionalshard_end",
                    in:"rftoolsbase:dimensionalshard"
                },{
                    out:"draconicevolution:end_draconium_ore",
                    in:"draconicevolution:draconium_dust"
                }
            ]
            endorecraft.forEach((ore)=>{
                e.custom({
                    "type":"mekanism:combining",
                    "mainInput":{
                        "amount":8,
                        "ingredient":{
                            "item":ore.in
                        }
                    },
                    "extraInput":{
                        "ingredient":{
                            "tag":"forge:end_stones"
                        }
                    },
                    "output":{
                            "item":ore.out
                        }
                    })
                })


    
})