
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 775507
	#The name of the modpack
	modpackName = "ROBOSS Factory I"
	#The version of the modpack
	modpackVersion = "V1.1.3"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

